### PR TITLE
[WIP] LiveTL Pane

### PR DESCRIPTION
**Pull request by KentoNishi**
## THIS PR IS STILL A DRAFT

This PR mounts the LiveTL interface in place of TLdex. It will bring these new features:
* MChad and LiveTL API integration
* TL Read-aloud mode
* Exporting selected TLs as screenshots
* Downloading selected TLs in text format
* Temporary TLer isolation
* Customizable spam protection
* General bug fixes (ex. display links and emotes properly)

The dynamically loaded component is `105.15kb (uncompressed) / 29.02kb (brotli)`, and additional modules (ex. screenshot rendering engine) are loaded only when the user requests them.

### Todo before upgrading to full PR:
- [ ] Connect UI to `tlHistory` entries
- [ ] Set up purgecss for tailwind
- [ ] Tweak the UI to fit smaller screens a bit better
- [ ] Clean up dev environment and source code

### Preview:
image

### CODE REVIEW

**Comment by RiceCakess** [comment]
Hey Kento, I took a look at the code. I'm going to be fairly honest here and straightforward, this looks super scuffed and probably cause headaches for both sides. There's three major pain points that in retrospect makes no sense for us to pursue. 1. Iframing the entire thing means the browser has a ton of overhead, and forces it to redownload major fonts and icons that already exists in the Holodex context. 2. Increasing complexity in build processes by injecting svelte into a Vue project. 3. the fact that we have an existing framework and ui library makes it especially questionable to shoehorn svelte, smelte? and tailwind? (not sure what's powering the ui side of LiveTL). We are really sorry about this after all the effort you put in so far. We didn't want you to invest any more time when we were still trying to decide if it is doable.

**Comment by KentoNishi** [comment]
Your points are very valid, and I totally understand. Thanks for the early heads up!

I have a couple things I want to say regarding each of the three points. Please don't take any of em personally, just arguing for the sake of argument.
1. Iframing the entire thing means the browser has a ton of overhead, and forces it to redownload major fonts and icons that already exists in the Holodex context. 
    * mounting actually works perfectly fine without using an iframe. i initially mounted it using a component adapter (which btw is tiny) and it worked fine. the only reason for using an iframe at the moment is because @r2dev2 strongly preferred it. adapter also allows for passing reactive props, so passing `tlHistory` is very doable
    * we don't use any icons outside of the material design icon set already imported by holodex. in theory there won't be double downloads if cached properly by the service worker + non-issue if we don't use an iframe
2. Increasing complexity in build processes by injecting svelte into a Vue project.
    * Fair point. Pre-building is a thing for svelte, so moving the entire svelte build process out of the dex build is also very doable. Bundle size will be unaffected, and it'll be loaded thru a dynamic import
    * The config is actually pretty simple, the tailwind and postcss config files literally just pass the config from our module to vite lolmao
3. the fact that we have an existing framework and ui library makes it especially questionable to shoehorn svelte, smelte? and tailwind?
    * smelte is basically tiny vuetify for svelte, and smelte uses tailwind classes. smelte very smol and so is tailwind after purgecss (which i admittedly have not set up).

Just to reiterate, the stuff above is just for the sake of argument. I don't intend to push forward with this if you feel it's not something you want, even if we address iframe and build complexity concerns. @r2dev2 might join the conversation a bit later cuz we had a discussion and he had some things to say. Do let me know your thoughts!

On an unrelated note, is there a way I can contribute to the TL socket backend? The LiveTL API for community captions and livetls is coming soon, so I'd like to work on bringing that to dex too.

**Comment by r2dev2** [comment]
Could you give feedback on whether the following plan seems like something that could be integrated into Holodex?

1. We pre-build LiveTL on our end and distribute the html, css, and js as a static site that can be hosted on your server or on github pages. This keeps all our build and implementation shenanigans out of Holodex.
2. We load LiveTL in an iframe and use `postMessage` to change it's state. The only postMessages needed should be

* new translations from your server
* user's timestamp in the video
* if the user said to load all the translations
* livetl settings that can be synchronized to a Holodex account
* livetl settings whenever they change (would be sent from livetl's iframe to holodex)

I prefer the iframe method over publishing the exported svelte app since if we go the exported svelte app way, we'd just be doing `.$set()` instead of `postMessage` and an iframe keeps the two apps separate which ensures a lack of coupling and license compatibility. Handling translations in a LiveTL embed with this plan could also reduce Holodex complexity by offloading the management of all the translation state to a separate program.

**Comment by RiceCakess** [comment]
Both of those plans seems like it would rely on an iframe. My assumption is that svelte can be compiled down to a generic javascript/html/css bundle that can be loaded in like any library. That was the pretense, but given the size of the application and the difficulty in reusing assets and runtimes it's not looking too convincing, which is unavoidable given the circumstances. 

But after giving it more thought on both our end and LiveTL's end, I'm not exactly sure which part of this plan is a good idea: 

- The majority of the complexity comes from our socket and custom message objects, which will continue to be maintained as it is unique to our system. This meant that the chat object going to LiveTL also requires extra handling, and custom built version of LiveTL.
- The best approach to handling Mchad (and maybe LiveTL api?), is to listen in from our backend do the data transformation and feed it through the existing socket, saving the client the overhead of listening to 3 different feeds.
- Lots of effort to shrink the package size to something suitable for web, which you guys did much better than expected 👏, but this goes back to needing to build a new custom LiveTL. In my opinion, it would have been far easier to just have users install the extension or maybe implement the functionality into the existing Holodex XD

I think we tried to force this way too hard, there were clearly better approaches and not really saving any trouble. I think what you guys got with LiveTL is great, I see a lot of holodex users using it, especially Hyperchat + multiview

**Pull request closed without merging**
