### PR TITLE
Next - adding multiview toolbar skeleton

### PR DESCRIPTION
**Pull request by trash-lobster**
Unsure what the preference for control of orgs selection is, but at the moment, chose to use the default orgs and adding in the extra options like favorites in manually. Next step is to show the live streams that are related to the orgs as icons next to the selection dropbox

### CODE REVIEW

**Comment by trash-lobster** [comment]
Current UI bug: once icons are populated from choice being made, the toolbar's length is expanded to ignore the side bar being opened.

**Comment by sphinxrave** [comment]
can you add some screenshots so these are easier to review :P

**Comment by trash-lobster** [comment]
Yup, for sure.

image
- When you open the drop down list

image
- after selecting an org [favorites has not been implemented just yet] 
- You will see that the bar now has the length that it should have when the sidebar is expanded

image
- when you hover over an icon

Additional notes:
- currently the length of the stream is a hardcoded placeholder
- stream image is directly retrieved through a fetch call to i.ytimg
- not mobile responsive

**Comment by sphinxrave** [comment]
well it's something :+1:

**Comment by sphinxrave** [comment]
Thanks for the PR <3

**Pull request merged**
