### PR TITLE
TLdex ko support

### PR DESCRIPTION
**Pull request by alexkoala**

### CODE REVIEW

**Comment by RiceCakess** [comment]
This will also need to be configured on the backend. Could I get a list what Korean live tl-ers are using to denote a TL like [kr] [en] [eng]? 

For example for zh:

there's 4 possibilities for the thing inside the parenthesis  'zh', '中文', 'tc', 'CHT',
and 5 possibilities for brackets [ ], ( ),「 」,『』, 【 】

**Comment by alexkoala** [comment]
> This will also need to be configured on the backend. Could I get a list what Korean live tl-ers are using to denote a TL like [kr] [en] [eng]? 
> 

[ko] [kor] [kr] [한글] [한국어]

**Comment by RiceCakess** [comment]
So no special brackets? will just track `(ko/kor/kr/한글/한국어)` and `[ko/kor/kr/한글/한국어]`

**Comment by alexkoala** [comment]
> So no special brackets?

Yes.

**Review by sphinxrave — APPROVED** [review]

**Pull request merged**
